### ISSUE TITLE
APIs are throwing "unauthorized" after implementing policies

### ISSUE THREAD

**Issue by jonathonbyrdziak** [merchantprotocol/capital-audience-support#22]
Issue Brief
--

What is the purpose of this issue:
been having issues accessing the api. I'm able to generate the access token fine, but when I try to use it for a get request it keeps returning "unauthorized". 

I've just did some more tests and I noticed that the "profiles" get request works, but the "pixels" and "visitor logs" requests just return an "unauthorized" error.

Investigating the ROLES I see that the policies are implemented.

I assume the problem is that the API controller is not honoring the policies properly

When was this bug experienced: Jan 23rd 2023

Resources
--

https://jmp.sh/CTLd3SLX+/Screen+Shot+2023-01-23+at+2.32.44+PM.png

Steps to reproduce
--

1. 
2. 

Actual result
--

1. 
2. 

Expected result
--

- [ ]

**Comment by tajim** [comment]
Hello @jonathonbyrdziak 

I had previously sent you a message on FB regarding this issue but we are still seeing the "This action is unauthorized." message when trying to fetch the Visitor Log.

Commenting here to be in the loop.

Let us know when this issue is fixed so we can build out our dashboard for visitor logs.

Regards

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/2275650/215085921-5237b10a-e254-4847-bbdd-e192bcad85a9.png">

**Comment by jonathonbyrdziak** [comment]
this was fixed
